Style/Encoding:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/LineLength:
  Max: 160

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.1

Style/StringLiterals:
  Enabled: false
